project:
  type: website
  output-dir: docs

website:
  title: "mlcolangelo.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - projects.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    

editor: visual

