---
title: "Resume"
project: 
  type: website
  output-dir: docs
  
website:
  title: "website-demo1"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Projects.qmd
---

MIA COLANGELO

Huntington Beach, CA / Fort Collins, CO

[MIALAUREN929\@GMAIL.COM](mailto:MIALAUREN929@GMAIL.COM)

714.916.8335

# **EDUCATION**

## COLORADO STATE UNIVERSITY

### *Fort Collins, Colorado                  August 2023 - May 2027*

·       Major in Ecosystem Science and Sustainability, working towards a B.S.

·       Minor in Geospatial Information Science (GIS)

·       University Honors Program

GPA: 3.45

## HUNTINGTON BEACH HIGH SCHOOL

### *Huntington Beach, California              August 2019-June 2023*

●      10+ AP/Honors Classes, 4 years of Student Leadership

GPA: 4.32

# WORK EXPERIENCE

**Colorado State University**

**Knapp Lab (DRE and SRRE Research Projects)**

· Assist with weekly measurements which include soil moisture, soil respiration (LICOR), photosynthesis, and phenology photos.

· Collect, identify, sort, and weigh biomass, including various grasses and flowering species.

· Prepared plots for new research project (SRRE).

**CSU Bookstore**

· Cashiering, Assisting Customers, Answering Phones, Straightening Merchandise

· Fulfilling Textbook Preorders and Online Orders

· Creating a welcoming place for students, faculty, staff, and guests to shop. 

#### *Honors Peer Mentor* 

#### ·   Planned and carried out curriculum designed to set first-year students up for success in college and careers.

·  Met individually with students regarding degree planning and

### Huntington Beach Academy for the Performing Arts

#### *Summer Camp Counselor/Staff                      2021 - 2023 (seasonal)*

· Led a group of 20+ first and second grade students in tactile and performance art activities.

· Managed camp sales and parent contact for over 150 campers, as well as conflict resolution and organizational tasks.

#### *Director’s Asst./Production Asst.       Sept. 2021-June 2023*

· Helped organize and manage cast members and run rehearsals for several shows.

· Provided technical stage support during middle school and high school level shows.

# ACTIVITIES

Collar Scholars at CSU     (2023-)

·       Outreach Coordinator, Puppy Sitter, and Puppy Raiser (Future Service Dog Aribella)

·       2 semesters as an officer, 260+ hours of volunteer puppy sitting

 

Bassic Acapella                    (2023-)

·       Event/Showcase Coordinator (2024-)         

 

Academy for the Performing Arts (APA) Student Council    (2019-2023)

# **AWARDS**

***Tower Award Nominee***

(Biological Science, 2022; English Composition & Musical Theater, 2023)                                              

                                                           

***APA Academy Award for Involvement*** (2023)                                           

***National Merit Scholarship***     (2023)

 

 

# **SKILLS**

·       Microsoft Office

·       Mass digital communication

·       Digital/graphic design

·       Canva, Procreate

·       Conflict resolution

·       Child management

·       Group leadership

·       Field research

·       ArcGIS Pro
